export const metaKeywords =[
"Camera stores South Africa",
"Best camera shops in South Africa",
"Buy cameras online South Africa",
"DSLR cameras South Africa",
"Mirrorless cameras South Africa",
"Camera accessories South Africa",
"Photography equipment South Africa",
"Camera rentals South Africa",
"Affordable cameras South Africa",
"Professional camera shops",
"Photography gear South Africa",
"Camera lenses South Africa",
"Used cameras South Africa",
"Camera repair services South Africa",
"Compact cameras South Africa",
"Action cameras South Africa",
"Camera tripods South Africa",
"Camera bags South Africa",
"South African photography stores",
"Online camera sales South Africa",
"Instant cameras South Africa",
"Camera deals South Africa",
"Best camera brands South Africa",
"Digital cameras South Africa",
"Film cameras South Africa",
"Camera workshops South Africa",
"Photography classes South Africa",
"Camera accessories online",
"Photography lighting equipment",
"Camera drones South Africa",
"High-end cameras South Africa",
"Entry-level cameras South Africa",
"Camera insurance South Africa",
"Photography studio equipment",
"Camera lenses for beginners",
"Specialty camera stores South Africa",
"Camera deals and discounts",
"New camera releases South Africa",
"Photography competitions South Africa",
"Camera tutorials South Africa",
]